<section id="about">
    <h2>Qui sommes nous ?</h2>
    <div class="people">

        <div class="">
            <img src="/images/mariane.webp" alt="Mariane" />
            <p>Mariane Gahengi</p>
        </div>
        <div class="">
            <img src="/images/serge.webp" alt="Serge"/>
            <p>Serge Pingitore</p>
        </div>
    </div>
    <p>
        La Team Pinpin est 
        composée d’un frère et d’une soeur ainsi que de la fille de cette dernière.
         En travaillant ensemble sur leur projet littéraire et artistique, ils ont
          pu créer des histoires plus vivantes et mémorables, ainsi que renforcer les
           thèmes et les émotions présents dans le texte. 
        Team Pinpin est le résultat d’une expérience familiale enrichissante et complice.
    </p>
</section>


